-- ============================================================================
-- DEPRECATED — do not run this file, and do not add tables to it.
--
-- This was a hand-maintained mirror of the schema created by migrate.js. The
-- two drifted badly and silently broke fresh provisions:
--
--   * users.reset_expires  vs  users.reset_token_expires
--       auth.controller.js queries reset_token_expires, so password reset was
--       completely broken on any database built from this file.
--   * documents.uploaded_by_id  vs  documents.uploaded_by
--       documents.controller.js queries uploaded_by, so document listing and
--       upload were broken here too.
--   * Missing entirely: folders (+ documents.folder_id), notification_logs,
--       push_delivery_retries, and all four calendar_* and both teams_* tables
--       — meaning /api/folders, /api/calendar and /api/teams could not work.
--
-- Keeping two independently maintained sources of truth is what caused those
-- bugs, so the mirror is gone rather than repaired.
--
-- ---------------------------------------------------------------------------
-- To provision a database, run the migration instead:
--
--     npm run db:migrate            # node src/config/migrate.js
--
-- migrate.js is idempotent (every statement is CREATE TABLE / CREATE INDEX /
-- ADD COLUMN "IF NOT EXISTS") and wrapped in a single BEGIN/COMMIT, so it is
-- safe to run repeatedly and against an existing database. It is the single
-- source of truth for the schema and matches the live database.
--
-- The standalone migrate-*.js scripts in this directory remain for applying
-- individual modules to an already-provisioned database; their contents are
-- mirrored into migrate.js so a from-scratch build matches a migrated one.
-- ---------------------------------------------------------------------------
--
-- This file is intentionally left without DDL. Nothing in the codebase reads
-- or executes it.
-- ============================================================================
